# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Healthy Heart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Healthy Heart

  target 'Healthy HeartTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Healthy HeartUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Core'

end
